language: node_js

node_js:
- '8'
- '9'
- '10'
- '11'

script:
- node test/test-app.js

before_script:

after_success:

# Trigger a push build on master/release and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

deploy:
  # runs semantic-release on each
  - provider: script
    # script: npm ci && npx semantic-release
    script: npm ci
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
      node: '8'
