language: node_js

node_js:
- '8'
- '9'
- '10'
- '11'

script:
- node test/test-app.js

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

after_success:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# Trigger a push build on master/release and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

deploy:
  # runs semantic-release on each
  - provider: script
    script: npm ci && npx semantic-release
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
      node: '8'
